### PR TITLE
Added More Words

### PR DESCRIPTION
**Pull request by clydehenry3**
Adding the  following words 

 (PASSORT) SHOULD SAY "PASSPORT" 
-----
* Algorithm 
* Archive 
* ATM
* Audio
* Bluetooth 
* Browser
* Cafe 
* Chat 
* Chatbox
* Cinema
* Compass
* Cricket (Animal)
* Cricket (Sport) 
* Cuisine
* Cursor 
* Delete
* Dolphin
* Download
* Email
* Emoji
* Ethernet
* Facebook
* Firewall
* Folder
* Font
* Gaming
* GIF
* GPS
* Inbox
* Keyboard
* Laptop
* Login 
* Logout
* Notification 
* Offline
* Passport - Needs to be fixed 
* Perfume
* Pixel
* Playlist
* Popcorn
* Pop-Up
* Sea Food
* Seasoning 
* Selfie
* Server
* Smartphone
* Spam
* Spice
* Starring 
* Tablet 
* Taxi
* Tiger
* Trek
* Upload
* Visa
* Webcam
* Website
* Wireless
* Yoga

### CODE REVIEW

**Comment by clydehenry3** [comment]
@srbmaury I made my first PR with 61 new words and one word needs to be changed - "passort" should say "passport".

**Comment by srbmaury** [comment]
How adding only English words without Hindi meaning going to contribute to this project?

**Comment by clydehenry3** [comment]
I'm sorry. Did I understand the issue wrong? It said that I only had to provide the English and strictly said not to provide Hindi. 

Unfortunately, English is my only language I speak.

**Comment by clydehenry3** [comment]
@srbmaury Is there a way we can work collaboratively together on this? Or how can we move forward? I would love to use a translator for Hindi but what if the information is wrong, misinterpreted, and in correct.

**Comment by srbmaury** [comment]
I used chatGPT to translate your words and found that it worked correctly.
For now you may use this to update your PR.
Algorithm : "एल्गोरिदम", Archive : "संग्रहण", ATM : "स्वचालित लेनदेन मशीन",
Audio : "ऑडियो", Bluetooth : "ब्लूटूथ", Browser : "ब्राउज़र", Cafe :
"कैफ़े", Chat : "चैट", Chatbox : "चैटबॉक्स", Cinema : "सिनेमा", Compass :
"कंपास", Cricket (Animal) : "कीट", Cricket (Sport) : "क्रिकेट", Cuisine :
"खाना-पीना", Cursor : "कर्सर", Delete : "मिटाना", Dolphin : "डॉल्फिन",
Download : "डाउनलोड", Email : "ईमेल", Emoji : "इमोजी", Ethernet : "ईथरनेट",
Facebook : "फेसबुक", Firewall : "फ़ायरवॉल", Folder : "फ़ोल्डर", Font :
"फॉन्ट", Gaming : "गेमिंग", GIF : "जिफ़", GPS : "ग्लोबल पोजीशनिंग सिस्टम",
Inbox : "इनबॉक्स", Keyboard : "कीबोर्ड", Laptop : "लैपटॉप", Login :
"लॉगइन", Logout : "लॉगआउट", Notification : "सूचना", Offline : "ऑफलाइन",
Passport : "पासपोर्ट", Perfume : "इत्र", Pixel : "पिक्सेल", Playlist :
"प्लेलिस्ट", Popcorn : "पॉपकॉर्न", Pop-Up : "पॉप-अप", Seafood : "समुंदरी
खाद्य", Seasoning : "मसाला", Selfie : "सेल्फ़ी", Server : "सर्वर",
Smartphone : "स्मार्टफ़ोन", Spam : "स्पैम", Spice : "मसाला", Starring :
"मुख्य भूमिका", Tablet : "टैबलेट", Taxi : "टैक्सी", Tiger : "बाघ", Trek :
"ट्रेक", Upload : "अपलोड", Visa : "वीज़ा", Webcam : "वेबकैम", Website :
"वेबसाइट", Wireless : "वायरलेस", Yoga : "योग",

**Comment by clydehenry3** [comment]
Got it. I'll do this moving forward. Thanks.

**Pull request merged**
